text = "Notepad is a simple text editor for Microsoft Windows and a basic text-editing program which enables computer users to create documents. It was first released as a mouse-based MS-DOS program in 1983, and has been included in all versions of Microsoft Windows since Windows 1.0 in 1985. \
    History Microsoft introduced Multi-Tool Notepad, a mouse-based text editor written by Richard Brodie, with the $195 Microsoft Mouse in May 1983 at the Spring COMDEX computer expo in Atlanta. Also introduced at that COMDEX was Multi-Tool Word,\
     designed by Charles Simonyi to work with the mouse.[1][2][3] Most watching Simonyi's demonstration had never heard of a mouse.[4] Microsoft released the Microsoft Mouse in June 1983,\
     and the boxed mouse and Multi-Tool Notepad began shipping in July.[5] Initial sales were modest, as there was little one could do with it except run the three demonstration programs included in the box (a tutorial, practice application and Notepad) \
         or program interfaces to it.[6] The Multi-Tool product line began with expert systems for the Multiplan spreadsheet.[7][8] On the suggestion of Rowland Hanson, who also convinced Bill Gates to change the name 'Interface Manager' to 'Windows' before the release of Windows 1.0,\
     the Multi-Tool name was killed by the time Word shipped in November 1983. Hanson's rationale was that 'the brand is the hero'. People didn't associate the stand-alone name Multi-Tool with Microsoft, and Hanson wanted to make Microsoft the hero, so the Microsoft name replaced 'Multi-Tool'.\
          Notepad has appeared on Microsoft Store twice. The first time was in August 2019; it vanished shortly thereafter.[9] This version would run on the preview versions of Windows 10, build number 18963 or later.[10] During this short-lived presence on the Store,\
               technology news blogs speculated that even though Notepad will still be included in Windows out of the box, as of Windows 10 version 20H1,\
     Notepad will no longer be a component of the operating system and updated through the bi-yearly Windows 10 version updates. The speculators believed that it will instead be a separate application receiving updates through the Microsoft Store. This will allow updates to the app to be delivered more frequently.[10][11] This did not happen in version 20H1 or its next version, 20H2.\
          Notepad appeared on Microsoft Store for a second time in April 2020, this time, sporting a new logo. It runs on the preview versions of Windows 10, build number 19541 or later.[9][12] Features Notepad is a common text-only (plain text) editor. The resulting files—typically saved with the .txt extension—have no format tags or styles, \
         making the program suitable for editing system files to use in a DOS environment and, occasionally, source code for later compilation or execution, usually through a command prompt. It is also useful for its negligible use of system resources; making for quick load time and processing time, especially on under-powered hardware. \
             Notepad supports both left-to-right and right-to-left based languages. Most versions of Notepad do not interpret newlines in Unix- or classic Mac OS-style text files as actual newlines. However, on May 8, 2018, Microsoft announced that they had fixed this issue in Windows 10.[13] Notepad offers only the most basic text manipulation functions, such as finding text. \
                 Only newer versions of Windows include an updated version of Notepad with a search and replace function.\
              However, it has much less functionality in comparison to full-scale editors. In all versions of Windows, Notepad uses a built-in window class named EDIT and the maximum file size that Notepad can open is dependent on operating system limitations on the size of the EDIT window class, with the limit being different for each version of Windows. Due to the operating system limit of the EDIT window class,\
                   the Notepad version shipped with Windows 3.0, Windows 3.1 and Windows 3.11 could not open files larger than 54 KB (kilobytes) and Microsoft recommended not to open files larger than 45 KB, with the official workaround advice provided by Microsoft being 'Use another text editor'\
         ,[14] but this limit was extended to 64 KB in Windows 95 (and remained the same in Windows 98 and Windows Me), with users now directed to WordPad to open larger files. On the Notepad version shipped with Windows XP the limit was 32 MB (megabytes) with the application displaying the message 'The file is too large for Notepad. Use another editor to edit the fil' \
             if the user attempted to open a file larger than 32 MB.[15] Newer versions of Notepad can open files at least up to 58 MB (megabytes) in size,[16] and on Windows 8.1 the Notepad application is able to open files at least as large as 512 MB (megabytes) but fails to open 1 GB (gigabyte) files displaying the same message that Windows XP users would see \
                 ('The file is too large for Notepad. Use another editor to edit the file').[17]  Up to Windows 95, Fixedsys was the only available display font for Notepad. Windows NT 4.0 and 98 introduced the ability to change this font. As of Windows 2000, the default font was changed to Lucida Console. The font setting, however, only affects the font the text is rendered in and printed in, not how the file is saved to disk. \
                 The default font was changed to Consolas on Windows 8. Up to Windows Me, there were almost no keyboard shortcuts and no line-counting feature. Starting with Windows 2000, shortcuts for common tasks like new, open and save were added, as well as a status-bar with a line counter (available only when word-wrap is disabled). In the Windows NT-based versions of Windows,\
                      Notepad can edit traditional 8-bit text files as well as Unicode text files (both UTF-8 and UTF-16, and in case of UTF-16, both little-endian and big-endian). Notepad also has a simple built-in logging function. Each time a file that starts with .LOG is opened, the program inserts a text timestamp on the last line of the file.[18][19] Notepad accepts text from the Windows clipboard.\
                          When clipboard data with multiple formats is pasted into Notepad, the program only accepts text in the CF_TEXT format.[20] This is useful for stripping embedded font type and style codes from formatted text, such as when copying text from a web page and pasting into an email message or other WYSIWYG text editor. Formatted text can be temporarily pasted into Notepad, and then immediately\
                               copied again in stripped format to paste into the other program.\
      Unicode superscripts with a space as in 98.6 ⁰ = 1 and 3 ² = 9, and subscripts without a space as in H₂O, can be understood in Notepad[original research?] due to Unicode support.Notepad can print files, but doesn't print correctly if Word Wrap is turned on. Headers, footers, and margins can be set and adjusted when preparing to print a file under Page Setup. The date, file name,\
           and other information can be placed in the headers and footers with various codes consisting of an ampersand ('&') followed by a letter."